Update MailerTests.cs
/app/tests/Exceptionless.Tests/Mail/MailerTests.cs(43,27): error CS7036: There is no argument given that corresponds to the required parameter 'email' of 'Mailer.Mailer(IQueue<MailMessage>, FormattingPluginManager, AppOptions, TimeProvider, ILogger<Mailer>, AWSEmail)' [/app/tests/Exceptionless.Tests/Exceptionless.Tests.csproj]